name: Release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-mate:
    name: Release Mate
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: release-mate/action@71f10a09c0b5161420efe386fdfa657f9f7d5688 # v1.1.1
        with:
          client-id: ${{ secrets.RELEASE_MATE_CLIENT_ID }}
          app-private-key: ${{ secrets.RELEASE_MATE_PRIVATE_KEY }}
